//Constructor
export const CLOSE_INFO = 'CLOSE_INFO'

export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST'
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS'
export const GET_ORDER_FAILED = 'GET_ORDER_FAILED'

export const GET_USER_ORDER_REQUEST = 'GET_USER_ORDER_REQUEST'
export const GET_USER_ORDER_SUCCESS = 'GET_USER_ORDER_SUCCESS'
export const GET_USER_ORDER_FAILED = 'GET_USER_ORDER_FAILED'

export const ADD_BUN = 'ADD_BUN'
export const ADD_FILLING = 'ADD_FILLING'
export const DELETE_FILLING = 'DELETE_FILLING'
export const MOVE_FILLING = 'MOVE_FILLING'

//Ingredients
export const GET_INGREDIENTS_REQUEST = 'GET_ITEMS_REQUEST'
export const GET_INGREDIENTS_SUCCESS = 'GET_ITEMS_SUCCESS'
export const GET_INGREDIENTS_FAILED = 'GET_ITEMS_FAILED'

//User
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST'
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'
export const USER_LOGOUT_FAILED = 'USER_LOGOUT_FAILED'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED'

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED'

export const USER_DATA_REQUEST = 'USER_DATA_REQUEST'
export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS'
export const USER_DATA_FAILED = 'USER_DATA_FAILED'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED'

export const ACCESS_TOKEN = 'accessToken'
export const REFRESH_TOKEN = 'refreshToken'

//WebSocket Orders
export const WS_ORDERS_CONNECT = 'WS_ORDERS_CONNECT'
export const WS_ORDERS_CONNECTING = 'WS_ORDERS_CONNECTING'
export const WS_ORDERS_DISCONNECT = 'WS_ORDERS_DISCONNECT'
export const WS_ORDERS_OPEN = 'WS_ORDERS_OPEN'
export const WS_ORDERS_CLOSE = 'WS_ORDERS_CLOSE'
export const WS_ORDERS_ERROR = 'WS_ORDER_CONNECTION_ERROR'
export const WS_ORDERS_MESSAGE = 'WS_ORDERS_MESSAGE'

//WebSocket Feeds
export const WS_FEEDS_CONNECT = 'WS_FEEDS_CONNECT'
export const WS_FEEDS_CONNECTING = 'WS_FEEDS_CONNECTING'
export const WS_FEEDS_DISCONNECT = 'WS_FEEDS_DISCONNECT'
export const WS_FEEDS_OPEN = 'WS_FEEDS_OPEN'
export const WS_FEEDS_CLOSE = 'WS_FEEDS_CLOSE'
export const WS_FEEDS_ERROR = 'WS_FEED_CONNECTION_ERROR'
export const WS_FEEDS_MESSAGE = 'WS_FEEDS_MESSAGE'

export const NORMA_WSS = 'wss://norma.nomoreparties.space/orders'
